### ISSUE TITLE
Std In Not Working

### ISSUE THREAD

**Issue by ManickYoj** [DakotaNelson/sneaky-creeper#25]
Maybe I'm interpreting the help text wrong, but it seems text is allowed as std in in a format like "./screep echo -e identity standard in text here", but it does not. Entering this text will create new lines with no way to submit.

What is the intended way to enter std in? Issue resolved either by fixing bug, if one exists, or updating the readme/helptext to explain how to submit std in.

**Comment by DakotaNelson** [comment]
You'll have to pipe it in (I put some examples in the readme yesterday).

`echo "some text" | ./screep ...`

That said, the fact that it just hangs if not given input is a known issue that should really be solved with an error message that actually says what's wrong instead of just hanging and being confusing.

**Comment by DakotaNelson** [comment]
When it "hangs" you can feed it input by typing and then hitting `Ctrl+D`, so I'm going to go ahead and close this. It's documented, it's standard practice for *nix from what I understand, and I think it'll work for now.
