### ISSUE TITLE
decode takes in a string cast of data[0] which makes it very difficult to work with.

### ISSUE THREAD

**Issue by byronwasti** [DakotaNelson/sneaky-creeper#27]
When trying to receive data and then decode it, we currently have the receive function of modules return a list. This list then has it's first element cast to a string as the sole input to the decoder. 

Why does data need to be returned as a list, and why are we only using the first element of the list for decoding?

**Comment by DakotaNelson** [comment]
Can you give me a line number? I'm not sure what you're referring to. (Also
on my phone, so that may be the problem.)

The reason it's returned as a list is so that we can have packets - since
e.g.Twitter can only send small amounts of data, we have to break it up.
There's a case to be made for doing that in the module code, but right now
it's in screep.

I'll take a closer look when I'm on my laptop.

**Comment by byronwasti** [comment]
A line number would have been good!
screep line 254.

Returning as a list makes total sense; casting to string on the first element makes less sense.

**Comment by DakotaNelson** [comment]
Yeah, you're right, [that spot in the code](https://github.com/DakotaNelson/sneaky-creeper/blob/master/screep#L254) doesn't make sense.

Quick hotfix: for element in array, decode it, then return all of the decoded elements as a comma separated string.

Longer term solution: figure out some way to make packets work: how do we reassemble them? Does the module code have to do that? What if there legitimately are two messages? How do we deal with multiple messages (especially if you run multiple times, how do you know not to retrieve (and act on) the old messages)?

**Comment by DakotaNelson** [comment]
This is strongly tied to #35. They'll likely be resolved together.

**Comment by DakotaNelson** [comment]
This is closed by #38.
