### ISSUE TITLE
Dropbox channel - decoding issue

### ISSUE THREAD

**Issue by davinerd** [DakotaNelson/sneaky-creeper#79]
When using the Dropbox channel:

```
(venv)srv@ubuntu:~/sneaky-creeper$ python screep 
['aes', 'b64', 'identity', 'lendiansteganography', 'rsa']
['dropboxc', 'file', 'googleDocs', 'soundcloudChannel', 'tumblrText', 'twitter']
{'sending': {'token': 'xxx', 'rfile': 'test.txt'}, 'receiving': {'token': 'xxx', 'lfile': 'testolina.txt', 'rfile': 'test.txt'}}
Traceback (most recent call last):
  File "screep", line 27, in <module>
    print t.receive()
  File "/home/srv/sneaky-creeper/sneakers/exfil.py", line 150, in receive
    for msg in reversed(data):
TypeError: argument to reversed() must be a sequence

(venv)srv@ubuntu:~/sneaky-creeper$ cat testolina.txt 
a b dmVyeSBzZWNyZXQgYW5kIHByaXZhdGUgbWVzc2FnZQ==

(venv)srv@ubuntu:~/sneaky-creeper$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import base64
>>> base64.b64decode('dmVyeSBzZWNyZXQgYW5kIHByaXZhdGUgbWVzc2FnZQ==')
'very secret and private message'
>>> 
```

**Comment by DakotaNelson** [comment]
The error is [here](https://github.com/DakotaNelson/sneaky-creeper/blob/master/sneakers/exfil.py#L150).

I think what's happening is that the messages aren't returned from the dropbox channel as an array. Is that the case? The framework will try to iterate through that array of messages (each of which should contain one message as a string with the format `a b dmVyeSBzZWNyZXQgYW5kIHByaXZhdGUgbWVzc2FnZQ==` as you have above, in this case) and attempt to parse each of them.

You're right, though, this would be a great place to put some error checking and a useful error messages so that module writers have some idea how to deal with this in the future.

**Comment by davinerd** [comment]
Dropbox's APIs simply download a file.

I guess we need your FileType adapter thing to get rid of this error.

EDIT:
My fault. The API allows you to download the content of the file. Now it's fixed, should work.

**Comment by DakotaNelson** [comment]
Awesome! @davinerd, can you open a PR for this?

**Comment by davinerd** [comment]
I was thinking to make a fundamental change on the code: why we require that the return value is a list when we can enforce it on `exfil.py` send() ? It wouldn't be a better idea to cast the return value of the module's `receive()` to list in the exfil class?

**Comment by DakotaNelson** [comment]
I think it's sort of worrying to just cast whatever we get to a list and use it.

Sure, it does need to be a list, but more than that, it needs to be a _specific_ list, of messages one at a time. If we just cast to a list and don't raise an error, then (for example) the module writer could return a string, have it cast to a list, and then spend a long time wondering why their module isn't working.

I think the better approach is to check to see if we're returned a list, then raise an exception with a useful error message if not so that module writers can understand what's actually going on under the hood enough to ensure their code is interfacing with the framework properly.
